common/models/Attributes.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "attributes".
 *
 * @property integer $id
 * @property string $title
 * @property integer $required
 * @property integer $apply_to_simple
 * @property integer $apply_to_grouped
 * @property integer $apply_to_configurable
 * @property integer $apply_to_virtual
 * @property integer $apply_to_bundle
 * @property integer $apply_to_downloadable
 * @property integer $system
 * @property string $code
 * @property string $field
 * @property string $validation
 * @property integer $configurable
 */
class Attributes extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */

    public $attributeGroupId;
    public $productTypeApplicableUpdate;
    public $productTypeApplicable;

    public static function tableName()
    {
        return 'attributes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['required', 'apply_to_simple', 'apply_to_grouped', 'apply_to_configurable', 'apply_to_virtual', 'apply_to_bundle', 'apply_to_downloadable', 'system', 'configurable'], 'integer'],
            [['field'], 'string'],
            [['title'], 'string', 'max' => 45],
            [['code', 'validation'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Attribute Title',
            'required' => 'Required',
            'apply_to_simple' => 'Apply To Simple',
            'apply_to_grouped' => 'Apply To Grouped',
            'apply_to_configurable' => 'Apply To Configurable',
            'apply_to_virtual' => 'Apply To Virtual',
            'apply_to_bundle' => 'Apply To Bundle',
            'apply_to_downloadable' => 'Apply To Downloadable',
            'system' => 'System',
            'code' => 'Attribute Code',
            'field' => 'Attribute   Field',
            'validation' => 'Validation',
            'configurable' => 'Configurable',
            'attributeGroupId' => 'Applay for ',
            'productTypeApplicableUpdate' => 'Applicable for ',
            'productTypeApplicable' => 'Applicable for ',
        ];
    }
}

backend/controllers/AttributesController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Attributes;
use common\models\search\AttributesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\components\AdminController;
use common\models\AttributeOptions;
/**
 * AttributesController implements the CRUD actions for Attributes model.
 */
class AttributesController extends AdminController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Attributes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AttributesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Attributes model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Attributes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Attributes();
        $input_type_dropdown=0;

        if(isset($_POST['Attributes'])){
            if($_POST['Attributes']['attributeGroupId']=='1'){
                $model->apply_to_simple = 1;
                $model->apply_to_bundle = 1;
                $model->apply_to_grouped = 1;
                $model->apply_to_configurable = 1;
                $model->apply_to_virtual = 1;
                $model->apply_to_downloadable = 1;
            }
            else {
                $model->apply_to_simple = 0;
                $model->apply_to_bundle = 0;
                $model->apply_to_grouped = 0;
                $model->apply_to_configurable = 0;
                $model->apply_to_virtual = 0;
                $model->apply_to_downloadable = 0;
                $sel_pro_type=$_POST['Attributes']['productTypeApplicable'];
                if($sel_pro_type!=''){
                    $sel_pro_type_count=count($sel_pro_type)-1;
                    for($i=0;$i<=$sel_pro_type_count;$i++){                    
                        if($sel_pro_type[$i]=='Simple'){$model->apply_to_simple = 1;}
                        if($sel_pro_type[$i]=='Bundle'){$model->apply_to_bundle = 1;} 
                        if($sel_pro_type[$i]=='Grouped'){$model->apply_to_grouped = 1;}
                        if($sel_pro_type[$i]=='Configurable'){ $model->apply_to_configurable = 1;}
                        if($sel_pro_type[$i]=='Virtual'){$model->apply_to_virtual = 1;}
                        if($sel_pro_type[$i]=='Downloadable'){$model->apply_to_downloadable = 1;}             
                    }
                }   
            }
            $model->required=$_POST['Attributes']['required'];
            $model->configurable=$_POST['Attributes']['configurable'];
            $model->validation=$_POST['Attributes']['validation'];            
            if($_POST['Attributes']['field']=='dropdown' || $_POST['Attributes']['field']=='multiselect'){
                $input_type_dropdown=1;
            }
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            
            if($input_type_dropdown==1 && isset($_POST['AttributeOptions']['value'])){
                foreach ($_POST['AttributeOptions']['value'] as $key => $attr_value) {
                    //echo $_POST['AttributeOptions']['value'][$i-1];
                    $model1= new AttributeOptions();
                    $model1->value=$attr_value;
                    $model1->attribute_id=$model->id;
                    $model1->save(false);
                }
                // exit;
            }
            return $this->redirect(['index']);

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Attributes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {   

        $model = $this->findModel($id);
        
        $input_type_dropdown=0;  
        if(isset($_POST['Attributes'])){         
            if($_POST['Attributes']['attributeGroupId']=='1'){
                $model->apply_to_simple = 1;
                $model->apply_to_bundle = 1;
                $model->apply_to_grouped = 1;
                $model->apply_to_configurable = 1;
                $model->apply_to_virtual = 1;
                $model->apply_to_downloadable = 1;
            }
            else {
                $sel_pro_type=$_POST['Attributes']['productTypeApplicableUpdate'];          
                if($sel_pro_type!=''){
                    $model->apply_to_simple = 0;
                    $model->apply_to_bundle = 0;
                    $model->apply_to_grouped = 0;
                    $model->apply_to_configurable = 0;
                    $model->apply_to_virtual = 0;
                    $model->apply_to_downloadable = 0;
                    $sel_pro_type_count=count($sel_pro_type)-1;
                    for($i=0;$i<=$sel_pro_type_count;$i++){
                        if($sel_pro_type[$i]=='Simple'){$model->apply_to_simple = 1; }
                        if($sel_pro_type[$i]=='Bundle'){$model->apply_to_bundle = 1; }
                        if($sel_pro_type[$i]=='Grouped'){$model->apply_to_grouped = 1; }
                        if($sel_pro_type[$i]=='Configurable'){$model->apply_to_configurable = 1;}
                        if($sel_pro_type[$i]=='Virtual'){$model->apply_to_virtual = 1;}
                        if($sel_pro_type[$i]=='Downloadable'){$model->apply_to_downloadable = 1;}
                    }
                }   
            }
            $model->required=$_POST['Attributes']['required'];
            $model->configurable=$_POST['Attributes']['configurable'];
            $model->validation=$_POST['Attributes']['validation']; 
            if($_POST['Attributes']['field']=='dropdown' || $_POST['Attributes']['field']=='multiselect'){
                $input_type_dropdown=1;
            }
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()){
            if($input_type_dropdown==1){ 
                $att_op_values=$_POST['AttributeOptions']['value']; 
                //var_dump($att_op_values);die;
                foreach ($att_op_values as $index => $option){ 
                    if(!$attributeOption = AttributeOptions::find()->where(['value' => $option, 'attribute_id' => $model->id])->one()){ //die($option);
                        $attributeOption = new AttributeOptions;
                    }
                    $attributeOption->value=$option;
                    if($attributeOption->value!=''){
                        $attributeOption->attribute_id=$model->id;
                        $attributeOption->save(false);
                    }
                }
            }
            return $this->redirect(['index']);
        } 
        else {
            return $this->render('update', ['model' => $model,]);                    
        }
    }

    /**
     * Deletes an existing Attributes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionDeleteAttributeOption(){    
        
        $id=$_POST['id'];
        $attibutesoption=AttributeOptions::findOne($_POST['id']);
        $attibutesoption->delete(false);
        return $id;
    }

    /**
     * Finds the Attributes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Attributes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Attributes::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/attributes/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\Attributes;
use common\models\AttributeOptions;

/* @var $this yii\web\View */
/* @var $model common\models\Attributes */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="attributes-form">
<?php $form = ActiveForm::begin(); ?>
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="false">Product Attribute</a></li>
            <li id="m_title" class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">Manage Titles (Size, Color, etc.)</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab_1">

                <div class="row">
                    <div class="col-sm-6 col-xs-12">
                        <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
                        <?= $form->field($model, 'code')->textInput() ?>
                        <?= $form->field($model, 'field')->dropDownList(['text' => 'Text Field', 'textarea' => 'Text Area','date' => 'Date', 'boolean' => 'Boolean','multiselect' => 'Multiple Select','dropdown' => 'Dropdown', 'price' => 'Price']); ?>
                        <?php
                            if ($this->context->action->id == 'update') {
                                $att= Attributes::find($model->id)->where(['id' => $model->id])->one();
                                if($att['apply_to_simple']=='0' || $att['apply_to_grouped']=='0' || $att['apply_to_configurable']=='0' || $att['apply_to_virtual']=='0' || $att['apply_to_bundle']=='0' || $att['apply_to_downloadable']=='0')
                                    {
                                        $model->attributeGroupId='2';
                                    }
                                }
                        ?>
                        <?= $form->field($model, 'attributeGroupId')->dropDownList(['1' => 'All Product Types', '2' => 'Selected Product Types']); ?>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                        <div id="spt">
                            <?php
                            $attr_selected[]=0;
                            if ($this->context->action->id == 'update') {
                                $att= Attributes::find($model->id)->where(['id' => $model->id])->one();                        
                                //print_r($att);
                                if($att['apply_to_simple']=='1') { $attr_selected[]='Simple';}
                                if($att['apply_to_grouped']=='1') { $attr_selected[]='Grouped';}
                                if($att['apply_to_configurable']=='1') { $attr_selected[]='Configurable';}
                                if($att['apply_to_virtual']=='1') { $attr_selected[]='Virtual';}
                                if($att['apply_to_bundle']=='1') { $attr_selected[]='Bundle';}
                                if($att['apply_to_downloadable']=='1') { $attr_selected[]='Downloadable';}
                                
                                $data = array('Simple' => 'Simple','Grouped' => 'Grouped','Configurable' => 'Configurable','Virtual' => 'Virtual','Bundle' => 'Bundle','Downloadable' => 'Downloadable',); 
                                $htmlOptions = array('multiple' => 'true');
                                echo $form->field($model,'productTypeApplicableUpdate')->listBox($data, $htmlOptions);
                            }?> 

                            <?php 
                            if ($this->context->action->id == 'create') {
                                $data = array('Simple' => 'Simple','Grouped' => 'Grouped','Configurable' => 'Configurable','Virtual' => 'Virtual','Bundle' => 'Bundle','Downloadable' => 'Downloadable',); 
                                $htmlOptions = array('multiple' => 'true');
                                echo $form->field($model,'productTypeApplicable')->listBox($data, $htmlOptions);
                            }
                            ?>                  
                        </div>

                         
                        <?= $form->field($model, 'required')->dropDownList(['0' => 'No', '1' => 'Yes']); ?>
                        <?= $form->field($model, 'validation')->dropDownList([ 'decimal' => 'Decimal Number','integer' => 'Integer Number','email' => 'Email','url' => 'URL','letters' => 'Letters(a-z)(A-Z) or Numbers(0-9)'],['prompt'=>'Select']); ?>
                        <div id="drop_conf">
                            <?= $form->field($model, 'configurable')->dropDownList(['0' => 'No', '1' => 'yes']); ?>
                        </div>

                        <div class="form-group">
                            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success theme-btn pull-right' : 'btn btn-primary theme-btn pull-right']) ?>
                        </div> 
                    </div>
                </div>
        
            </div><!-- /.tab-pane -->
            <div class="tab-pane " id="tab_2">

            <div class="btn-group pull-right">
                <a class="btn btn-primary theme-btn" onclick="addRow('dataTable')"> <i class="fa fa-plus"> </i> Add </a>
                <a class="btn btn-danger theme-btn" id="remove_last_row"> <i class="fa fa-minus"> </i> Remove </a>
            </div>
            
                            <div class="slimScroll">
                                <?php $model1= new AttributeOptions();?>
                                <?php if ($this->context->action->id == 'update') { ?>
                                    <?php
                                    $att_options = AttributeOptions::find()->where(['attribute_id' => $model->id])->all();
                                    foreach ($att_options as $index => $att_options_id) {?>
                                        <table id="dataTable1" width="50%">
                                            <tr id="<?=$att_options_id['id']?>"><td width="90%">                    
                                            <?= $form->field($model1, 'value['.$att_options_id['id'].']')->textInput(['class'=>'disabled form-control','readonly' => !$model->isNewRecord,'value'=>$att_options_id['value']])->label(false) ?></td>
                                            <td width="10%"><span class="man-title cursor-link" id="<?=$att_options_id['id']?>"><i class="fa fa-close"></i></span>                            
                                            </td></tr>
                                        </table>
                                    <?php }
                                } ?>
                                <table id="dataTable" width="50%">
                                    <tr>
                                        <td width="90%"><?= $form->field($model1, 'value[]')->textInput(['maxlength' => 45])->label(false) ?></td>
                                        <td width="10%"></td>
                                    </tr>
                                </table>
                            </div> 

                                <div class="form-group">
                                    <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success theme-btn pull-right' : 'btn btn-primary theme-btn pull-right']) ?>
                                </div>

                                <div class="clearfix"> </div>
                                
                            
       
    
            </div><!-- /.tab-pane -->
            <div class="tab-pane" id="tab_3">
            
        
            </div><!-- /.tab-pane -->
        </div><!-- /.tab-content -->
    </div>

    




    


   


<?php ActiveForm::end(); ?>
</div>


<script type="text/javascript">

    function addRow(tableID){
        var table=document.getElementById(tableID);
        var rowCount=table.rows.length;
        var row=table.insertRow(rowCount);
        var colCount=table.rows[0].cells.length;
        for(var i=0;i<colCount;i++){
            var newcell=row.insertCell(i);
            newcell.innerHTML=table.rows[0].cells[i].innerHTML;
            switch(newcell.childNodes[0].type){
                case"text":newcell.childNodes[0].value="";break;
                case"checkbox":newcell.childNodes[0].checked=false;break;
                case"select-one":newcell.childNodes[0].selectedIndex=0;break;
            }
        }
    }


    $(document).ready(function(){       
        $("#remove_last_row").click(function() {
            var count = $('#dataTable tr').length;
            if(count>1) {
                $('.attributes-form #dataTable tr:last').remove();
            }
            else {
                swal(
                  'Sorry!',
                  'You have removed maximum!',
                  'error'
                );
            }
            
        });


        $("#attributes-producttypeapplicableupdate option").each(function(){            
            <?php foreach ($attr_selected as $index => $attr_sel)  {?>
                if ($(this).text() == "<?=$attr_sel?>")
                $(this).attr("selected","selected");
            <?php } ?> 
        });
        if ($('#attributes-field').val() == 'dropdown' || $('#attributes-field').val() == 'multiselect'){
            $("#m_title").show();    
            $("#drop_conf").show();
            $("#manage_title").show();                    
        }
        else
            {

            $("#m_title").hide();   
            $("#drop_conf").hide();
            $("#manage_title").hide();
        }

        if ($('#attributes-attributegroupid').val() == '2'){
            $("#spt").show();
        }
        else {
            $("#spt").hide();
        }
    
        $('#attributes-attributegroupid').on('change', function() {
            if ( this.value == '2'){
                $("#spt").show();
            }
            else{
                $("#spt").hide();
            }
        });    
        $('#attributes-field').on('change', function() { 
            if ( this.value == 'dropdown' || this.value == 'multiselect'){
                $("#m_title").show();    
                $("#drop_conf").show();
                $("#manage_title").show();
            }
            else {
                $("#m_title").hide();    
                $("#drop_conf").hide();
                $("#manage_title").hide();
            }
        }); 
    });


    $(document).ready(function(){
        $(".man-title").click(function(){




            if(confirm("Are you sure you want to delete this item?..")){
                $.ajax({
                    type: "POST",
                    url: "<?=Yii::$app->urlManager->createUrl(['attributes/delete-attribute-option'])?>",             
                    data: "&id=" + this.id ,
                    dataType: "html", 
                    success: function (data) {                         
                        $("#"+data).hide(); 
                        $("#attributeoptions-value-"+data).val('');

                    }                 
                }); 
            }
            else{
                return false;
            }            
        });
    });



</script>



<script> 
$( document).ready(function() {

  var screenHeight = $(window).height();
  $ ( '.slimScroll' ).slimScroll({
        height: screenHeight-300

    });
    
}); 
</script>

backend/views/attributes/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\AttributesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="attributes-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'required') ?>

    <?= $form->field($model, 'apply_to_simple') ?>

    <?= $form->field($model, 'apply_to_grouped') ?>

    <?php // echo $form->field($model, 'apply_to_configurable') ?>

    <?php // echo $form->field($model, 'apply_to_virtual') ?>

    <?php // echo $form->field($model, 'apply_to_bundle') ?>

    <?php // echo $form->field($model, 'apply_to_downloadable') ?>

    <?php // echo $form->field($model, 'system') ?>

    <?php // echo $form->field($model, 'code') ?>

    <?php // echo $form->field($model, 'field') ?>

    <?php // echo $form->field($model, 'validation') ?>

    <?php // echo $form->field($model, 'configurable') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/attributes/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Attributes */

$this->title = 'Create Attributes';
$this->params['breadcrumbs'][] = ['label' => 'Attributes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="attributes-create">

   

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/attributes/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\AttributesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Attributes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="attributes-index">

    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Attributes', ['create'], ['class' => 'btn btn-success theme-btn pull-right']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'title',
            'required'=>[
                'header' =>'Required',
                'value' => function($model, $attribute){ return $model->required=="1"? "Required" : "Not Required"; },
                'filter' => \yii\helpers\Html::activeDropDownList($searchModel, 'required', ['1' => 'Required', '0' => 'Not Required'],['class'=>'form-control','prompt' => 'All']),
            ],
            
            'apply_to_simple'=>[
                'header' =>'Simple product',
                'value' => function($model, $attribute){ return $model->apply_to_simple=="1"? "Yes" : "No"; },
                'filter' => \yii\helpers\Html::activeDropDownList($searchModel, 'apply_to_simple', ['1' => 'Yes', '0' => 'No'],['class'=>'form-control','prompt' => 'All']),
            ],

            'configurable'=>[
                'header' =>'configurable product',
                'value' => function($model, $attribute){ return $model->configurable=="1"? "Yes" : "No"; },
                'filter' => \yii\helpers\Html::activeDropDownList($searchModel, 'configurable', ['1' => 'Yes', '0' => 'No'],['class'=>'form-control','prompt' => 'All']),
            ],
            // 'apply_to_virtual',
            // 'apply_to_bundle',
            // 'apply_to_downloadable',
            // 'system',
            // 'code',
            // 'field',
            // 'validation',
            // 'configurable',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/attributes/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Attributes */

$this->title = 'Update Attributes: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Attributes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="attributes-update">

    

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/attributes/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Attributes */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Attributes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="attributes-view">

    

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'required',
            'apply_to_simple',
            'apply_to_grouped',
            'apply_to_configurable',
            'apply_to_virtual',
            'apply_to_bundle',
            'apply_to_downloadable',
            'system',
            'code',
            'field',
            'validation',
            'configurable',
        ],
    ]) ?>

</div>