common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use common\models\B2bAddress;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getB2bAddressModel() {
        return $this->hasOne(B2bAddress::className(),['user_id'=>'id']);
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use backend\components\AdminController;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends AdminController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {   
        return $this->render('index');
    }

    public function actionLogin()
    {
        $this->layout='loginLayout';
        if (!Yii::$app->user->isGuest) {
            
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } 
        else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\UrlKey;
use backend\models\CmsPage;
use backend\models\search\UserSearch;
use common\models\Products;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                  //  'logout' => ['post'],
                ],
            ],
        ];
    }

    
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionDealersAccount() {

        if (!Yii::$app->user->isGuest) {
                   echo'<pre>';
                   print_r("re direction works here"); die();
        }

        $model = new LoginForm();
        if($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('dealers-account', [
                'model' => $model,
            ]);
        }
    }

    public function actionDealerSignup() {

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if(!empty($user)) {
                    return $this->render('dealer-signup-confimation',[
                        'user' => $user,
                    ]);
                }
            }
        }

        return $this->render('dealer-signup', [
            'model' => $model,
        ]); 
    }

    public function actionStoreLocator() {

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->post());
        $dataProvider->query->andWhere(['level'=>'5','is_approved'=>'success']);
        $dataProvider->pagination->pageSize = 1;

        return $this->render('store-locator',[
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            

        ]);

    }

    


    public function actionIndex()
    {   
         //Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.]');
        return $this->render('index');
    }

    public function actionTest() {
        
        return $this->render('mine');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {   


        Yii::$app->getSession()->setFlash('error', 'This is the message');
        
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                // Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                // Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionSlug($slug) {

        $slugRecord = UrlKey::find()->where(['url_key'=>$slug])->one();
        if(!empty($slugRecord)) {
            if($slugRecord->type=='product') {
                $productModel = Products::findOne($slugRecord->product_id);

                return $this->render('/products/view',[
                    'model'=> $productModel,
                ]);
            }
            else if($slugRecord->type=='cms') {

                $cmsPage = CmsPage::findOne($slugRecord->page_id);
                return $this->render('cmsView',['model'=>$cmsPage]);       
            }
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionProduct()
    {
        return $this->render('product');
    }

    public function actionProduct_view()
    {
        return $this->render('product_view');
    }

    public function actionStores()
    {
        return $this->render('stores');
    }

    public function actionDealers_login()
    {
        return $this->render('dealers_login');
    }

    public function actionDealers_home()
    {
        return $this->render('dealers_home');
    }

    public function actionDealers_product_view()
    {
        return $this->render('dealers_product_view');
    }

    

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/_store-view.php
   


    <div class="col-sm-6 information-entry">
        <div class="login-box" style="margin-top: 0px !important;margin-bottom: -23px !important;">
            <div class="article-container style-1">
                <h3 style="text-transform: uppercase;"><?= $model->b2bAddressModel->shop_name ?></h3>
                <h4 style="text-transform: uppercase;"><?= $model->b2bAddressModel->place ?></h4> 
                <h5>Company address</h5>
                <p><?= $model->b2bAddressModel->address ?><br>
                <?= $model->b2bAddressModel->place ?><br>
               <?= $model->b2bAddressModel->district ?><br>
               <!--  CA 90896<br> 
                United States<br> --></p>
                <h5>Contact Informations</h5>
                <p> <span><i class="fa fa-user"></i>&nbsp <?= $model->display_name ?></span><br>
                    <span><i class="fa fa-envelope"></i>&nbsp <?= $model->email ?></span><br>
                <span><i class="fa fa-phone-square"></i>&nbsp <?= $model->b2bAddressModel->mobile ?></span></p>
            </div>
        </div>
    </div>

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use backend\components\widgets\CmsBlocks;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>

<style type="text/css">
section.page-view {
   background: rgba(194, 163, 37, 0.48);
}

#content-block *:last-child {
    margin-bottom: 8px !important;
}

.article-container h5, .h5 {   
    color: #b51717 !important;   
}

.article-container {   
    color: #000000 !important;    
}

.project-thumbnail { 
    margin-bottom: 10px !important; 
}
.about-border {
    border: solid;
    margin-bottom: 12px;
    padding: 7px 15px 0px 20px;
    border-color: #b7a972;
}
</style>

<div class="container">
	<div class="raw margin-top-min-75">
		<div class="site-about">
			<div id="content-block">

		        <div class="content-center fixed-header-margin">
		           
		          <img class="project-thumbnail" src="/themes/shopping/img/banner.jpg" alt="" />

		            <div class="content-push">

		               

		                <div class="information-blocks">
		                    <div class="row">

		                    	<?= CmsBlocks::widget(['code'=>2])?>
		                 

		                        <div class="col-md-4 information-entry">
		                            <div class="accordeon">
		                                <div class="accordeon-title"> <?= CmsBlocks::widget(['code'=>3])?> </div>
		                                <div class="accordeon-entry" style="display: none;">
		                                    <div class="article-container style-1">
		                                        <?= CmsBlocks::widget(['code'=>4])?> 
		                                    </div>
		                                </div>
		                                <div class="accordeon-title"><?= CmsBlocks::widget(['code'=>5])?> </div>
		                                <div class="accordeon-entry" style="display: none;">
		                                    <div class="article-container style-1">
		                                        <?= CmsBlocks::widget(['code'=>6])?>
		                                    </div>
		                                </div>
		                               
		                            </div>
                                </div>                   
		                    </div>
		                </div>
		                
		                
		            </div>
		        </div>
		        <div class="clear"></div>
		    </div>
		</div>
	</div>	
</div>

frontend/views/site/cmsView.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use backend\components\widgets\CmsBlocks;

$this->title = $model->meta_title;
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="container">
	<div class="row">
		<div class="Col-xs-12">
			<h2 style="font-size: 26px; text-decoration: underline; text-transform: uppercase;"> <?= $model->title?> </h2>
		</div>
		<div class="col-xs-12" style="padding: 10px; padding-top: 30px;">
			<?= $model->content ?>
		</div>
	</div>	
</div>

frontend/views/site/dealer-signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Url;
use kartik\alert\Alert;

$this->title = 'Dealers Accounts';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container">
    <div class="raw margin-top-min-75" >
        <div class="site-contact">          
            <div id="content-block">
                <div class="content-center fixed-header-margin">
                    <div class="content-push">
                        <div class="information-blocks">
                            <div class="row">
                                <div class="col-sm-12 information-entry" style="padding-top: 10px;">
                                    <div class="login-box">
                                        <div class="article-container style-1">
                                            <h3>Dealers Registration </h3>
                                        </div>
                                    
                                        <div class="row">
                                            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                                            
                                            <div class="col-xs-12 col-sm-6">
                                                <?= $form->field($model, 'display_name')->textInput(['maxlength'=>true])->label('Contact Person') ?>
                                                <?= $form->field($model,'shop_name')->textInput(['maxlength'=>true,]) ?>
                                                <?= $form->field($model,'address')->textArea(['rows'=>3]) ?>
                                                <?= $form->field($model, 'place')->textInput(['maxlength'=>true]) ?>
                                                <?= $form->field($model, 'district')->textInput(['maxlength'=>true]) ?>

                                               
                                            </div>
                                            <div class="col-xs-12 col-sm-6">
                                                <?= $form->field($model, 'username')->textInput(['autofocus' => true,'maxlength'=>true]) ?>
                                                <?= $form->field($model, 'email') ?>
                                                <?= $form->field($model, 'mobile')->textInput(['maxlength'=>true]) ?>
                                                <?= $form->field($model, 'password')->passwordInput(['maxlength'=>true]) ?>
                                                <?= $form->field($model, 'c_password')->passwordInput(['maxlength'=>true]) ?>
                                                <?= $form->field($model, 'reCaptcha')->widget(
                                                    \himiklab\yii2\recaptcha\ReCaptcha::className(),
                                                    ['siteKey' => '6LeEqjQUAAAAAKWcY0LBQ7xfvDhBG-bP8KP1fPvo']
                                                ) ?>

                                                 <div class="form-group">
                                                    <?= Html::submitButton('Signup', ['class' => 'button style-12 pull-right', 'name' => 'signup-button']) ?>
                                                </div>

                                            </div>
                                            <?php ActiveForm::end(); ?>
                                        </div>

                                       

                                            

                                            

                                            

                                        

                                     </div>
                                </div>
                                
                            </div>
                        </div>  
                    </div>
                </div>
                <div class="clear"></div>
            </div>  

        </div>
    </div>  
</div>

frontend/views/site/dealers_login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Dealers Login';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container">
    <div class="raw margin-top-min-75">
        <div class="site-contact">          
           
              <div id="content-block">

        <div class="content-center fixed-header-margin">

            <div class="content-push">
<!-- 
                <div class="breadcrumb-box">
                    <a href="/site/index">Home</a>
                    <a href="#">Login Form</a>
                </div> -->

                <div class="information-blocks">
                    <div class="row">
                        <div class="col-sm-6 information-entry">
                            <div class="login-box">
                                <div class="article-container style-1">
                                    <h3>Registered Dealers</h3>
                                </div>
                                <form action="/site/dealers_home">
                                    <label>Limax Username</label>
                                    <input class="simple-field" type="text" placeholder="Username" value="" />
                                    <label>Limax Password</label>
                                    <input class="simple-field" type="password" placeholder="Password" value="" />
                                    <div class="button style-10">Login Here<input type="submit" value="" /></div>
                                </form>
                            </div>
                        </div>
                        <div class="col-sm-6 information-entry">
                            <div class="login-box">
                                <div class="article-container style-1">
                                    <h3>New Dealers</h3>
                                    <p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
                                </div>
                                <a class="button style-12">Register Here</a>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
        <div class="clear"></div>

    </div>  

        </div>
    </div>  
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>

<div class="container">
    <div class="row">
        <div class="site-error">

            <h1><?= Html::encode($this->title) ?></h1>

            <div class="alert alert-danger">
                <?= nl2br(Html::encode($message)) ?>
            </div>

            <p>
                The above error occurred while the Web server was processing your request.
            </p>
            <p>
                Please contact us if you think this is a server error. Thank you.
            </p>

        </div>

    </div>
</div>

frontend/views/site/index.php
<?php
use backend\components\widgets\CustomBanner;
/* @var $this yii\web\View */

$this->title = 'Limax Group';
?>
<section>
<div class="main-banner">
    <div class="tp-banner-container">
        <div class="tp-banner" >
            <ul>   
                <!-- SLIDE  1  -->
               
                
                <!-- SLIDE  2 -->
                <li data-transition="zoomout" data-slotamount="7" data-masterspeed="1000" >
                    <!-- MAIN IMAGE -->
                    <img src="/images/slide2a.png"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
                    <!-- LAYERS -->

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption customin"
                        data-x="474"
                        data-y="189"
                        data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                        data-speed="500"
                        data-start="800"
                        data-easing="Power3.easeInOut"
                        data-endspeed="300"
                        style="z-index: 2"><img src="/images/ago2-blue-2.png" alt="">
                    </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption customin"
                        data-x="245"
                        data-y="92"
                        data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                        data-speed="500"
                        data-start="500"
                        data-easing="Power3.easeInOut"
                        data-endspeed="300"
                        style="z-index: 3"><img src="/images/ago2-bw-5.png" alt="">
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption customin"
                        data-x="693"
                        data-y="69"
                        data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                        data-speed="500"
                        data-start="1300"
                        data-easing="Power3.easeInOut"
                        data-endspeed="300"
                        style="z-index: 4"><img src="/images/ago2-simple-1.png" alt="">
                    </div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption customin"
                        data-x="100"
                        data-y="171"
                        data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                        data-speed="500"
                        data-start="1400"
                        data-easing="Power3.easeInOut"
                        data-endspeed="300"
                        style="z-index: 5"><img src="/images/ago2-orange-1.png" alt="">
                    </div>
                </li>
                
                 <?= CustomBanner::widget([])?>
               
            </ul>
            <div class="tp-bannertimer"></div>
        </div>
    </div>
</section>
<section>
    <div class="container">
        <div class="row">
            <div class="demo loader" id="waitme">
        <p> dfdfdfdd </p>

    
    </div>

        </div>
    </div>
</section>
    



    <!-- THE SCRIPT INITIALISATION -->
    <!-- LOOK THE DOCUMENTATION FOR MORE INFORMATIONS -->
    <script type="text/javascript">

        function run_waitMe(effect){
    $('#waitme').waitMe({
        effect: 'facebook',
        text: 'Please wait...',
        bg: 'rgba(255,255,255,0.7)',
        color: '#000',
        sizeW: '',
        sizeH: '',
        source: '',
        onClose: function() {}
    });

}

        var revapi;

        jQuery(document).ready(function() {

               revapi = jQuery('.tp-banner').revolution(
                {
                    delay:9000,
                    startwidth:1170,
                    startheight:500,
                    hideThumbs:10,
                    fullWidth:"on",
                    forceFullWidth:"on"
                });

        }); //ready

    </script>

</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>